version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./content:/usr/share/nginx/content
    depends_on:
      - new_ui
  
  new_ui:
    build: new_ui
    volumes:
      - ./content:/content
    ports:
      - '5000:5000'


  # node:
  #   image: node:latest 
  #   user: "root"
  #   working_dir: /home/node/app
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - ./server:/home/node/app
  #     - ./content:/home/node/content
  #   expose:
  #     - "3000"
  #   command: sh -c "npm install && node index.js"


